"""
Seed script to populate the database with sample data for testing.
Run: python seed.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app import create_app
from models import db, Equipment, User
from datetime import date, datetime
import bcrypt
import random

app = create_app()

SAMPLE_DATA = [
    {
        'indicator': 'ICT-001',
        'procurement_title': 'Desktop Computer Unit',
        'supplier': 'PC Express',
        'location': 'IT Office',
        'type_of_equipment': 'Desktop',
        'brand': 'Dell',
        'model': 'OptiPlex 7080',
        'property_number': 'PROP-2024-001',
        'serial_number': 'SN-DELL-7080-001',
        'acquisition_date': date(2024, 1, 15),
        'cost': 45000.00,
        'description': 'Desktop computer with Intel i7, 16GB RAM, 512GB SSD',
        'person_accountable': 'Juan Dela Cruz',
        'person_accountable_position': 'IT Officer III',
        'used_by': 'Maria Santos',
        'used_by_position': 'Admin Aide IV',
        'with_warranty': True,
        'clear_monitor': True,
        'active_cmos_battery': True,
        'charging_ups': True,
        'working_io_ports': True,
        'updated_patched_os': True,
        'weekly_scan_antivirus': True,
        'working_keyboard_mouse': True,
        'remarks_recommendation': 'Unit in good condition',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'No repairs needed',
        'status': 'serviceable',
    },
    {
        'indicator': 'ICT-002',
        'procurement_title': 'Laptop Computer',
        'supplier': 'Octagon',
        'location': 'Accounting Office',
        'type_of_equipment': 'Laptop',
        'brand': 'Lenovo',
        'model': 'ThinkPad T14',
        'property_number': 'PROP-2024-002',
        'serial_number': 'SN-LEN-T14-002',
        'acquisition_date': date(2024, 2, 20),
        'cost': 55000.00,
        'description': 'Laptop with Intel i5, 8GB RAM, 256GB SSD',
        'person_accountable': 'Pedro Reyes',
        'person_accountable_position': 'Accountant II',
        'used_by': 'Ana Gonzales',
        'used_by_position': 'Accountant I',
        'with_warranty': True,
        'clear_monitor': True,
        'active_cmos_battery': True,
        'charging_ups': False,
        'working_io_ports': True,
        'updated_patched_os': True,
        'weekly_scan_antivirus': True,
        'working_keyboard_mouse': True,
        'remarks_recommendation': 'Battery needs replacement soon',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'Battery replacement scheduled',
        'status': 'serviceable',
    },
    {
        'indicator': 'ICT-003',
        'procurement_title': 'Network Printer',
        'supplier': 'DataLink',
        'location': 'Records Section',
        'type_of_equipment': 'Printer',
        'brand': 'HP',
        'model': 'LaserJet Pro M404dn',
        'property_number': 'PROP-2023-015',
        'serial_number': 'SN-HP-M404-003',
        'acquisition_date': date(2023, 8, 10),
        'cost': 18500.00,
        'description': 'Black and white laser printer with duplex printing',
        'person_accountable': 'Rosa Lim',
        'person_accountable_position': 'Records Officer II',
        'used_by': 'Rosa Lim',
        'used_by_position': 'Records Officer II',
        'with_warranty': False,
        'clear_monitor': False,
        'active_cmos_battery': False,
        'charging_ups': False,
        'working_io_ports': True,
        'updated_patched_os': False,
        'weekly_scan_antivirus': False,
        'working_keyboard_mouse': False,
        'remarks_recommendation': 'Toner needs replacement',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'Replaced fuser unit on 2024-03-15',
        'status': 'serviceable',
    },
    {
        'indicator': 'ICT-004',
        'procurement_title': 'UPS Battery Backup',
        'supplier': 'APC Direct',
        'location': 'Server Room',
        'type_of_equipment': 'UPS',
        'brand': 'APC',
        'model': 'Back-UPS 1100VA',
        'property_number': 'PROP-2022-008',
        'serial_number': 'SN-APC-1100-004',
        'acquisition_date': date(2022, 5, 5),
        'cost': 8500.00,
        'description': '1100VA UPS with 6 outlets',
        'person_accountable': 'Juan Dela Cruz',
        'person_accountable_position': 'IT Officer III',
        'used_by': 'Juan Dela Cruz',
        'used_by_position': 'IT Officer III',
        'with_warranty': False,
        'clear_monitor': False,
        'active_cmos_battery': False,
        'charging_ups': False,
        'working_io_ports': True,
        'updated_patched_os': False,
        'weekly_scan_antivirus': False,
        'working_keyboard_mouse': False,
        'remarks_recommendation': 'Battery no longer holds charge. Recommend replacement.',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'Battery replaced 2023-01-10. Battery failed again 2024-04-20.',
        'status': 'unserviceable',
    },
    {
        'indicator': 'ICT-005',
        'procurement_title': 'LCD Monitor 24"',
        'supplier': 'PC Express',
        'location': 'IT Office',
        'type_of_equipment': 'Monitor',
        'brand': 'Samsung',
        'model': 'S24F350FH',
        'property_number': 'PROP-2023-022',
        'serial_number': 'SN-SAM-S24-005',
        'acquisition_date': date(2023, 3, 18),
        'cost': 9800.00,
        'description': '24-inch Full HD LED Monitor',
        'person_accountable': 'Juan Dela Cruz',
        'person_accountable_position': 'IT Officer III',
        'used_by': 'Carlos Tan',
        'used_by_position': 'IT Staff',
        'with_warranty': True,
        'clear_monitor': True,
        'active_cmos_battery': False,
        'charging_ups': False,
        'working_io_ports': True,
        'updated_patched_os': False,
        'weekly_scan_antivirus': False,
        'working_keyboard_mouse': False,
        'remarks_recommendation': 'Good condition',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'None',
        'status': 'serviceable',
    },
    {
        'indicator': 'ICT-006',
        'procurement_title': 'Network Switch 24-Port',
        'supplier': 'Microdata',
        'location': 'Server Room',
        'type_of_equipment': 'Networking',
        'brand': 'Cisco',
        'model': 'SG350-28',
        'property_number': 'PROP-2023-030',
        'serial_number': 'SN-CIS-SG350-006',
        'acquisition_date': date(2023, 6, 22),
        'cost': 32000.00,
        'description': '28-Port Managed Gigabit Switch',
        'person_accountable': 'Juan Dela Cruz',
        'person_accountable_position': 'IT Officer III',
        'used_by': 'Juan Dela Cruz',
        'used_by_position': 'IT Officer III',
        'with_warranty': True,
        'clear_monitor': False,
        'active_cmos_battery': False,
        'charging_ups': False,
        'working_io_ports': True,
        'updated_patched_os': True,
        'weekly_scan_antivirus': False,
        'working_keyboard_mouse': False,
        'remarks_recommendation': 'Operational. Firmware updated.',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'None',
        'status': 'serviceable',
    },
    {
        'indicator': 'ICT-007',
        'procurement_title': 'Desktop Computer Unit',
        'supplier': 'Villman',
        'location': 'HR Office',
        'type_of_equipment': 'Desktop',
        'brand': 'HP',
        'model': 'ProDesk 400 G7',
        'property_number': 'PROP-2021-012',
        'serial_number': 'SN-HP-PD400-007',
        'acquisition_date': date(2021, 9, 12),
        'cost': 38000.00,
        'description': 'Desktop computer with Intel i5, 8GB RAM, 256GB SSD',
        'person_accountable': 'Lorna Bautista',
        'person_accountable_position': 'HRMO II',
        'used_by': 'Lorna Bautista',
        'used_by_position': 'HRMO II',
        'with_warranty': False,
        'clear_monitor': True,
        'active_cmos_battery': False,
        'charging_ups': True,
        'working_io_ports': False,
        'updated_patched_os': True,
        'weekly_scan_antivirus': True,
        'working_keyboard_mouse': True,
        'remarks_recommendation': 'CMOS battery needs replacement. 2 USB ports not working.',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'RAM upgrade from 4GB to 8GB on 2023-02-14',
        'status': 'serviceable',
    },
    {
        'indicator': 'ICT-008',
        'procurement_title': 'Multifunction Printer',
        'supplier': 'Octagon',
        'location': 'Accounting Office',
        'type_of_equipment': 'Printer',
        'brand': 'Epson',
        'model': 'L3210',
        'property_number': 'PROP-2020-005',
        'serial_number': 'SN-EPS-L3210-008',
        'acquisition_date': date(2020, 4, 8),
        'cost': 7200.00,
        'description': 'Inkjet multifunction printer - print, scan, copy',
        'person_accountable': 'Pedro Reyes',
        'person_accountable_position': 'Accountant II',
        'used_by': 'Pedro Reyes',
        'used_by_position': 'Accountant II',
        'with_warranty': False,
        'clear_monitor': False,
        'active_cmos_battery': False,
        'charging_ups': False,
        'working_io_ports': False,
        'updated_patched_os': False,
        'weekly_scan_antivirus': False,
        'working_keyboard_mouse': False,
        'remarks_recommendation': 'Print head damaged. Recommend disposal and replacement.',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'Print head cleaned 2022-06. Print head replaced 2023-01. Failed again 2024-02.',
        'status': 'unserviceable',
    },
    {
        'indicator': 'ICT-009',
        'procurement_title': 'Laptop Computer',
        'supplier': 'PC Express',
        'location': "Mayor's Office",
        'type_of_equipment': 'Laptop',
        'brand': 'ASUS',
        'model': 'VivoBook 15',
        'property_number': 'PROP-2024-035',
        'serial_number': 'SN-ASUS-VB15-009',
        'acquisition_date': date(2024, 4, 1),
        'cost': 42000.00,
        'description': 'Laptop with AMD Ryzen 5, 8GB RAM, 512GB SSD',
        'person_accountable': 'Elena Cruz',
        'person_accountable_position': 'Executive Assistant II',
        'used_by': 'Elena Cruz',
        'used_by_position': 'Executive Assistant II',
        'with_warranty': True,
        'clear_monitor': True,
        'active_cmos_battery': True,
        'charging_ups': False,
        'working_io_ports': True,
        'updated_patched_os': True,
        'weekly_scan_antivirus': True,
        'working_keyboard_mouse': True,
        'remarks_recommendation': 'New unit. All working.',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'None',
        'status': 'serviceable',
    },
    {
        'indicator': 'ICT-010',
        'procurement_title': 'Wireless Access Point',
        'supplier': 'Microdata',
        'location': 'Lobby',
        'type_of_equipment': 'Networking',
        'brand': 'TP-Link',
        'model': 'EAP245',
        'property_number': 'PROP-2023-041',
        'serial_number': 'SN-TPL-EAP-010',
        'acquisition_date': date(2023, 11, 5),
        'cost': 5500.00,
        'description': 'AC1750 Wireless MU-MIMO Gigabit Access Point',
        'person_accountable': 'Juan Dela Cruz',
        'person_accountable_position': 'IT Officer III',
        'used_by': 'Public',
        'used_by_position': 'N/A',
        'with_warranty': True,
        'clear_monitor': False,
        'active_cmos_battery': False,
        'charging_ups': False,
        'working_io_ports': True,
        'updated_patched_os': True,
        'weekly_scan_antivirus': False,
        'working_keyboard_mouse': False,
        'remarks_recommendation': 'Firmware updated. Operational.',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'None',
        'status': 'serviceable',
    },
    {
        'indicator': 'ICT-011',
        'procurement_title': 'Desktop Computer Unit',
        'supplier': 'Villman',
        'location': 'Records Section',
        'type_of_equipment': 'Desktop',
        'brand': 'Acer',
        'model': 'Veriton X2680G',
        'property_number': 'PROP-2022-019',
        'serial_number': 'SN-ACR-VX26-011',
        'acquisition_date': date(2022, 7, 14),
        'cost': 35000.00,
        'description': 'Desktop computer with Intel i3, 8GB RAM, 256GB SSD',
        'person_accountable': 'Rosa Lim',
        'person_accountable_position': 'Records Officer II',
        'used_by': 'Mark Villanueva',
        'used_by_position': 'Clerk I',
        'with_warranty': False,
        'clear_monitor': True,
        'active_cmos_battery': True,
        'charging_ups': True,
        'working_io_ports': True,
        'updated_patched_os': True,
        'weekly_scan_antivirus': True,
        'working_keyboard_mouse': True,
        'remarks_recommendation': 'Good working condition',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'HDD replaced with SSD on 2023-08-20',
        'status': 'serviceable',
    },
    {
        'indicator': 'ICT-012',
        'procurement_title': 'Projector',
        'supplier': 'Octagon',
        'location': 'Conference Room',
        'type_of_equipment': 'Projector',
        'brand': 'Epson',
        'model': 'EB-X51',
        'property_number': 'PROP-2022-025',
        'serial_number': 'SN-EPS-EBX51-012',
        'acquisition_date': date(2022, 2, 28),
        'cost': 28000.00,
        'description': '3800 Lumens XGA 3LCD Projector',
        'person_accountable': 'Juan Dela Cruz',
        'person_accountable_position': 'IT Officer III',
        'used_by': 'Shared',
        'used_by_position': 'N/A',
        'with_warranty': False,
        'clear_monitor': False,
        'active_cmos_battery': False,
        'charging_ups': False,
        'working_io_ports': True,
        'updated_patched_os': False,
        'weekly_scan_antivirus': False,
        'working_keyboard_mouse': False,
        'remarks_recommendation': 'Lamp hours nearing end of life. Plan for replacement.',
        'inventory_date': date(2024, 6, 1),
        'repair_history': 'Filter cleaned 2023-06. Lamp replaced 2023-12.',
        'status': 'serviceable',
    },
]


def seed():
    with app.app_context():
        # Check if data already exists
        if Equipment.query.count() > 0:
            print(f'Database already has {Equipment.query.count()} equipment records. Skipping seed.')
            return

        for data in SAMPLE_DATA:
            eq = Equipment(**data)
            db.session.add(eq)

        db.session.commit()
        print(f'Successfully seeded {len(SAMPLE_DATA)} equipment records.')


if __name__ == '__main__':
    seed()
